# Generated by Django 5.1.2 on 2024-12-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_published_date_post_date_posted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='published_date',
        ),
    ]
